import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, basename } from 'node:path';

const NEWS_DIR = 'content/news';
const OUT_FILE = 'src/app/pages/news/generated/news.generated.ts';

function parseFrontmatter(raw, filePath) {
  if (!raw.startsWith('---\n')) {
    throw new Error(`${filePath}: missing frontmatter block`);
  }

  const endIndex = raw.indexOf('\n---\n', 4);
  if (endIndex === -1) {
    throw new Error(`${filePath}: invalid frontmatter block`);
  }

  const frontmatterRaw = raw.slice(4, endIndex).trim();
  const markdown = raw.slice(endIndex + 5).trim();
  const frontmatter = {};

  for (const line of frontmatterRaw.split('\n')) {
    const sep = line.indexOf(':');
    if (sep === -1) continue;
    const key = line.slice(0, sep).trim();
    const value = line.slice(sep + 1).trim().replace(/^"|"$/g, '');
    frontmatter[key] = value;
  }

  return { frontmatter, markdown };
}

function guessExcerpt(markdown) {
  const lines = markdown
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith('#') && !line.startsWith('!['));

  const first = lines[0] || '';
  return first.replace(/\*\*|\*|`|\[|\]|\(|\)/g, '').slice(0, 220);
}

function createSlugFromFile(fileName) {
  return fileName.replace(/\.md$/i, '');
}

function main() {
  const files = readdirSync(NEWS_DIR)
    .filter((file) => file.toLowerCase().endsWith('.md'))
    .sort();

  const articles = files.map((fileName) => {
    const filePath = join(NEWS_DIR, fileName);
    const raw = readFileSync(filePath, 'utf8');
    const { frontmatter, markdown } = parseFrontmatter(raw, filePath);
    const slug = frontmatter.slug || createSlugFromFile(fileName);

    if (!frontmatter.title) {
      throw new Error(`${filePath}: missing required frontmatter field "title"`);
    }
    if (!frontmatter.date) {
      throw new Error(`${filePath}: missing required frontmatter field "date"`);
    }

    return {
      slug,
      title: frontmatter.title,
      date: frontmatter.date,
      excerpt: frontmatter.excerpt || guessExcerpt(markdown),
      sourceUrl: frontmatter.source_url || null,
      markdown
    };
  });

  articles.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

  const out = `/* Auto-generated by scripts/build-news.mjs. Do not edit manually. */\n` +
`export interface NewsArticleSource {\n` +
`  slug: string;\n` +
`  title: string;\n` +
`  date: string;\n` +
`  excerpt: string;\n` +
`  sourceUrl: string | null;\n` +
`  markdown: string;\n` +
`}\n\n` +
`export const NEWS_ARTICLES: NewsArticleSource[] = ${JSON.stringify(articles, null, 2)};\n`;

  writeFileSync(OUT_FILE, out, 'utf8');
  console.log(`Generated ${OUT_FILE} from ${files.length} Markdown files.`);
}

main();
